<?php require_once('roller.php'); ?>
<?php require_once('mutate.php'); ?>
<?php require_once('info.php'); ?>
<?php require_once('dice.php'); ?>
<?php //require_once('start-turn.php'); ?>
<?php require_once('add-power.php'); ?>
<?php require_once('edit-power.php'); ?>
<?php require_once('add-equipment.php'); ?>
<?php require_once('edit-equipment.php'); ?>